### ISSUE TITLE
Просьба

### ISSUE THREAD

**Issue by edgiru** [devicehive/esp8266-firmware#11]
Извините за тавтологию. Я интересовался, читал, много народу интересуется вашей разработкой и сервером devicehive но людям (особенно новичкам) не понятно что с этим всем делать. Документации крайне мало причем она и на английском еще. Хотелось бы попросить от имени интернет сообщества написать полноценную документацию, побольше примеров и пример мобильного клиента. Заранее спасибо, очень надеюсь что ответ будет положительным. И спасибо Вам огромное за проделанную большую работу.

**Comment by Nikolay-Kha** [comment]
Мы работаем над этим. На хабр планируется еще статьи.
Пример мобильного клиент существует - https://github.com/devicehive/android-ble
Он для андройда. Несмотря на то что там полноценный проект который позволяет управлять BLE устройствами через сервер DeviceHive, исходный код вполне пригоден для использования в качестве примера как использовать Java библиотеку на мобильном устройстве.
