### ISSUE TITLE
Ребят не забрасывайте проект

### ISSUE THREAD

**Issue by edgiru** [devicehive/esp8266-firmware#13]
Идея проекта очень классная, но вы почему то перестали ее развивать. Наверно нет времени. Жалко

**Comment by Nikolay-Kha** [comment]
Скоро будет кое что новенькое и интересное ;)

**Comment by edgiru** [comment]
Николай а где смотреть изменения? здесь или другой проект будет?

**Comment by Nikolay-Kha** [comment]
Здесь. Бранч develop - https://github.com/devicehive/esp8266-firmware/tree/develop
Предваритальный список нововедений:
- Поддержка популярных датчиков из коробки
- Локальный RESTful API
- Встроенный вебсервер с примерами использования
- Возможность загрузки своего контента на встроенный вебсервер
- mDNS
