### ISSUE TITLE
Проблема с прошивкой

### ISSUE THREAD

**Issue by Umasterov** [devicehive/esp8266-firmware#18]
Пытаюсь прошить ESP последней версией, но флешер не может найти порт, к которому подключена плата. При этом терминал находит порт и подключается к ESP. В чём может быть причина проблемы?

**Comment by Nikolay-Kha** [comment]
Попробуйте указать порт вручную. 
./esp-flasher /dev/ttyUSB0
или для windows
esp-flasher.exe COM4
Номера портов соотвественно замените.

**Comment by Nikolay-Kha** [comment]
Удалось ли прошить?

**Comment by Umasterov** [comment]
Не удалось, не находит устройство.
Можно как-то проверить работоспособность модуля ESP? При подключении питании один раз моргает синий диод и больше ничего не горит. При этом модуль сильно греется.
Да, и, скорее всего, на моём модуле уже установлена прошивка (помню, что ранее прошить его получалось)

**Comment by Nikolay-Kha** [comment]
Проверить можно. Нужно подключиться к серийному порту на скорости 74880(нестандартная скорость) и наблюдая вывод перезагрузить чип. При нормальном запуске должен быть такой вывод:
![image](https://cloud.githubusercontent.com/assets/8740775/22419955/e8208a7a-e6f0-11e6-95ad-abb31a65f315.png)
Подключиться можно например программой Putty ((в ней можно задать не стандартную скорость порта)
Этот вывод дает сам чип еще до старта прошивки. Если вывода нету - то чип умерший.
p.s. непонятные символы на скриншоте внизу - это уже вывод прошивки чипа, но т.к. скорость стоит 74880 получаются значки а не текст.

**Comment by Umasterov** [comment]
А какие пины и куда нужно при этом подключить?

**Comment by Nikolay-Kha** [comment]
просто нужно подключить USB конвертер к плате и замыкать пин RST на земля для перезагрузки.

**Comment by Umasterov** [comment]
Подключаюсь к порту через Putty. Пустой экран терминала. Подключаю RST к земле -- мигает диод на ESP, в терминале ничего не меняется. Отключаю RST от земли -- ещё раз мигает диод и опять ничего не меняется. Может дело в USB конвертере?

**Comment by Nikolay-Kha** [comment]
Может. Чтобы проверить USB переходник, нужно просто замкнуть выводы Rx и Tx, запустить терминал и все что печатается в терминал должно приходить обратно, т.е. должен  быть виден набираемый текст.

**Comment by Umasterov** [comment]
Подключаться через Putty на той же скорости?

**Comment by Nikolay-Kha** [comment]
да

**Comment by Umasterov** [comment]
У меня после ввода просто курсор в терминале перескакивает на начало строки.
Если разомкнуть, то ничего написать нельзя

**Comment by Nikolay-Kha** [comment]
При вводе текста  в окне терминала при замкнутых выводах RX и TX курсор перескакивает на начало строки? Я правильно понял?

**Comment by Umasterov** [comment]
Да, всё верно

**Comment by Nikolay-Kha** [comment]
И набираемых символов текста не видно вообще?

**Comment by Umasterov** [comment]
Если замкнуть RX и TX, то видно. Замыкаю, подключаюсь, пишу в терминале:
**test**I
Нажимаю ввод, получаю:
I**test**
Т.е. при этом просто курсор на начало строки перескакивает. Новые строки не добавляются. Так и должно быть?

**Comment by Nikolay-Kha** [comment]
да, такое бывает. Приложение просто посылает не верный символ возврата строки (\r вместо \n). Переходник рабочий.
Похоже что что-то с модулем, скорее всего где-то попросту нету контакта от самогой микросхемы по пинок RX или TX. Можно еще попробовать подключить пин RX переходника к пину GPIO2 (этот пин также должен дублировать данные передаваемы на TX) - возможно удасться что нибудь увидеть.
