### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by MaxLesichniy** [devicehive/esp8266-firmware#22]
Не получить собрать прошивку в eclipse. С чем могут быть связаны эти ошибки ?
![0tjanmsrz50](https://cloud.githubusercontent.com/assets/8543552/20649659/e03509a4-b4cc-11e6-821c-c724512a7257.jpg)
![k8p8kslx-pk](https://cloud.githubusercontent.com/assets/8543552/20649660/e0356f98-b4cc-11e6-8558-ebe5c7aff45e.jpg)

**Comment by Nikolay-Kha** [comment]
Стандарт языка Си видимо не тот. В gcc версии 4.х по умолчанию использовался gnu89. Начиная с пятой версии по умолчанию используется gnu11. Видимо у вас gcc 5 или более новой версии. Оригинальный SDK использует фичи, которые требуют стандарта gnu89. Так что, надо просто к CFLAGS добавить -std=gnu89 . Я явно указал это в последнем коммите бранча develop. Но можете по примеру этого коммита - https://github.com/devicehive/esp8266-firmware/commit/d47a4f448726f0fbadd17c3bf54e103ca959d71b добавить параметр к коду любой версии. Должно собраться.

**Comment by MaxLesichniy** [comment]
Все заработало, спасибо)
