### ISSUE TITLE
Дополнительный функционал в прошивке

### ISSUE THREAD

**Issue by molodoj88** [devicehive/esp8266-firmware#26]
Здравствуйте!

Подскажите, как можно добавлять новый функционал в прошивку? Например, при подключении к wi-fi изменять состояние некотороых пинов esp.

**Comment by Nikolay-Kha** [comment]
Здравствуйте. Для этого нужно пересобрать прошивку из исходников. Для этого нужно поставить тулченй для сборки. Мануал для установки тулчейна тут - https://github.com/esp8266/esp8266-wiki/wiki/Toolchain . Сам SDK ставить не обязательно, достаточно просто поставить crosstool-NG.
Затем в папке firmware-src позвать make и прошивка должна собраться в папку firmware-src\firmware.

При подключении к сети WiFi вызывается код с этого места - https://github.com/devicehive/esp8266-firmware/blob/master/firmware-src/sources/dhconnector.c#L349
Для управления GPIO см. https://github.com/devicehive/esp8266-firmware/blob/master/firmware-src/sources/dhgpio.h
