### ISSUE TITLE
примеры

### ISSUE THREAD

**Issue by edgiru** [devicehive/esp8266-firmware#4]
Я пытаюсь разобраться. т.к. я не программист а системщик пытаюсь начать с самого простого. Немного изменил Ваш пример. Но не работает висит на "Connecting... Refresh page for canceling." пробовал вручную командами в личном кабинете на devicehive все ок работает dht22 дает ответ.

подправил только тут: http://pastebin.com/zjfD26sk
(не вставляется тут в issue код html пришлось другим сайтом воспользоваться)

**Comment by Nikolay-Kha** [comment]
Достаточно поправить на 23 строке:
var PIN = 0;
на любой нужный пин, т.е. например для GPIO4 нужно написать:
var PIN = 4;
на той строке. Судя по коду по ссылке, вы хотите сделать формой. Тогда, форму надо поправить на:

```
<select name="gpio">
      <option disabled>Выберите GPIO:</option>
      <option value=0>gpio0</option>
      <option selected value=1>gpio1</option>
      <option value=2>gpio2</option>
 </select>
```

т.е. само значение номера gpio должно быть цифрой. И еще нужно добавить одну строку в функцию run:

```
function run(form){ 
    print("Connecting... Refresh page for canceling.", "black");
    localStorage["dhurl"] = form.url.value;
    localStorage["dhdeviceid"] = form.deviceid.value;
    localStorage["dhpassword"] = form.password.value; 
    PIN = parseInt(form.gpio.value);  // вот эту строку
    dht22 = form.dht.value == "dht22";  
    get_data(data_recevied);
}
```

p.s. для добавления кода используйте блок 
&#96;&#96;&#96;
ваш код
&#96;&#96;&#96;

**Comment by edgiru** [comment]
Доброе время суток.
Будут ли новые релизы и что интересного нас ждет в прошивках, хотелось бы узнать планы (если это не секрет фирмы)?
извините если Вам покажется вопрос глупым. почему все на английском в devicehive да и вообще в датаарт?

**Comment by Nikolay-Kha** [comment]
Здравствуйте.
Работы над релизом версии 0.4 идут. В новой версии будет поддержка новых плейграундов (мы недавно обновили сайт http://devicehive.com ) и возможно стоит ожидать появление режима энергогсбережения, но это пока не точно.
Датаарт это международная компания. Отсюда и английский язык.
