### ISSUE TITLE
NodeMCU v3 Lolin esp8266mod Hysiry нет подключения

### ISSUE THREAD

**Issue by phsin** [devicehive/esp8266-firmware#44]
прошивка выполнена успешно, 
![image](https://user-images.githubusercontent.com/5953570/36072346-d556cfec-0f37-11e8-9901-46c3844557c4.png)

после прошивки терминал не подключается к esp.
![image](https://user-images.githubusercontent.com/5953570/36072352-f2da197a-0f37-11e8-838b-3210ea7bc0b4.png)

esp-terminal-win.exe com10
порт не отвечает, не удается конфигурировать устройство

Подскажите, пожалуйста, как можно исправить?

**Comment by Nikolay-Kha** [comment]
попробуйте запустить 
esp-terminal-win.exe com10
т.е. указав порт вручную и перезагрузить саму плату. Будет ли вывод какой либо в терминале?

-> порт не отвечает, не удается конфигурировать устройство
не вижу подобного вывода на скриншотах. Если где-то подобные тексты проскакивают, значит возможен порт занят чем-то в системе - надо попробовать перезагрузить сам компьютер.

**Comment by phsin** [comment]
> попробуйте запустить
>esp-terminal-win.exe com10
>т.е. указав порт вручную и перезагрузить саму плату. Будет ли вывод какой либо в терминале?

подключается к com10, при перезагрузке платы выводятся не читаемые символы
![image](https://user-images.githubusercontent.com/5953570/36137673-b3daa3ec-10af-11e8-89be-6e021e252596.png)

**Comment by phsin** [comment]
http://forum.espruino.com/conversations/305323/ предлагают изменить адрес загрузки и частоту, 
как это сделать?

**Comment by Nikolay-Kha** [comment]
Судя по выводу - прошивки в чипе почему-то нету, хотя с NodeMCU v3 Lolin модулями обычно все работает. esp-flasher к сожалению не умеет менять частоту из параметров. Адрес загрузки менять нельзя - прошивка просто гарантированно не запуститься. Попробуйте прошить с помощью утилиты esptool ( https://github.com/espressif/esptool )
esptool.py -p com10 -b 115200 write_flash 0x00000 devicehive.bin
com10 измените на свой, если он поменялся.
аргумент -b задает частоту, попробуйте 115200, 74880 или на худой конец 19200.

**Comment by phsin** [comment]
Прошить получилось только с внешним источником питания на 3.3В минимум на 200мА, тот что на плате на 100мА. После прошивки флешером https://github.com/nodemcu/nodemcu-flasher плата стала отвечать в мониторе который идет с прошивкой.

![image](https://user-images.githubusercontent.com/5953570/37679854-a7ed491a-2c9b-11e8-9f8f-e098003dec6d.png)
