### ISSUE TITLE
esp-terminal can not detect port

### ISSUE THREAD

**Issue by yuchen-ecnu** [devicehive/esp8266-firmware#48]
I downloaded the v0.8 devicehive-esp8266-firmware and flash the firmware with the esp-flasher successfully . However, after the GPIO0 is unplugged and restarted the device , the device cannot be found using the esp-terminal tool.
The hardware I use is esp8266-01. Expect your help.
ps: when used `esp-terminal COM7 `, where were none output
![image](https://user-images.githubusercontent.com/19743175/37210378-83ca8464-23e3-11e8-8bdf-85e9371185f0.png)

**Comment by Nikolay-Kha** [comment]
Hello. What is the EEPROM chip on your module? That is a tiny 8pin chip nearby esp8266 itself. What is the label on it?
For example, I have module which works with 
25Q40BV
chip - that is 4MBit(512KByte) flash. This size is suitable for the firmware. The firmware is not working with less memory, and chip(and flasher as a result) doesn't return error on flashing.

And is there any output with `esp-terminal COM6(change to your port)` on chip reset?

**Comment by yuchen-ecnu** [comment]
Hi. I'm glad to receive your reply.
The EEPROM chip's label is "MD BX1642 MD25D80SIG P13472".
I check my chip's flash size.It is 8Mbits( i think it may be enough),just as the follow pic shows.
And there id no output with `esp-terminal COM6(my own port)` on chip reset.
![ey_m ye9b 5q9ld _1 6o](https://user-images.githubusercontent.com/19743175/38007738-6b1e33f4-327d-11e8-9466-23fc1eebb93d.png)

![k rxdzwu25 x yye4b 9 p](https://user-images.githubusercontent.com/19743175/38007776-aa5d8b1e-327d-11e8-95ad-13f7f0a3538f.png)
