### ISSUE TITLE
MPU-6050 and ESP8266

### ISSUE THREAD

**Issue by roccomuso** [devicehive/esp8266-firmware#5]
Can you share the scripts to connect the ESP-8266 to the MPU-6050 ? I'm using NodeMCU Lua and actually i got some issues working with the I2C and MPU-6050 :/

**Comment by Nikolay-Kha** [comment]
it's here: https://github.com/devicehive/esp8266-firmware/blob/master/examples/mpu6050-i2c.html

**Comment by roccomuso** [comment]
No i mean the code that handles the I2C...

**Comment by Nikolay-Kha** [comment]
Code is here. https://github.com/devicehive/esp8266-firmware/blob/master/firmware-src/sources/dhi2c.c
But if you are looking for lua code you will not find it here. Because DeviceHive firmware is written on pure C and based only on chip manufacturer SDK.
