### ISSUE TITLE
GY-271 Constant reporting

### ISSUE THREAD

**Issue by dmigo** [devicehive/esp8266-firmware#52]
There is a [GY-271](http://www.robotpark.com/image/data/PRO/91457/GY_271_ELECTRONIC_COMPASS.pdf) module connected to my nodemcu.
Devicehive playground allows me to read the data from i2c using the `i2c/master/read` command.  
What I want is to get the data as a constant flow. Is it possible to constantly read i2c? What is the best approach on that?

**Comment by Nikolay-Kha** [comment]
Hello, you can send requests continuously from your software or you would need to modify firmware to make it send results as notification continuously. You can find sample of such modification in this branch - https://github.com/devicehive/esp8266-firmware/tree/climate (but it was more complicated - it put device into sleep mode between notifications.
