### ISSUE TITLE
Ошибка с прошивкой

### ISSUE THREAD

**Issue by ghost** [devicehive/esp8266-firmware#7]
Можете подсказать из-за чего возникает данного рода ошибка?
![2015-11-03 23-01-36](https://cloud.githubusercontent.com/assets/6755508/10918476/4e7de16e-827f-11e5-985b-8d9ae88eef4c.png)
Заранее спасибо)

**Comment by edgiru** [comment]
было такое. попробуйте перезакачать архив (и на всякий случай: избегайте называть папки киррилицей)

**Comment by ghost** [comment]
Вот подстава.. похоже ночью работать не вариант. Проблема была в том, что в папке не было файлов *.bin для прошивки.. :+1: 
Спасибо за помощь)
