### ISSUE TITLE
Бесконечный "Send poll request..."

### ISSUE THREAD

**Issue by ghost** [devicehive/esp8266-firmware#8]
Ждал всю ночь, но после настройки устройства в dmesg было сообщение о том, что устройство успешно зарегистрировано и подключено к playground, но дальше следует бесконечное повторение строчки "Send poll request...". Что делать?

**Comment by ghost** [comment]
![2015-11-04 11-10-38](https://cloud.githubusercontent.com/assets/6755508/10931838/b7aeb720-82e4-11e5-81d9-defc19ba0483.png)

**Comment by Nikolay-Kha** [comment]
poll request означает что устройство успешно подключилось и посылает запрос на сервер с целью получения команды. Это нормальный рабочий цикл. У вас все работает.

**Comment by ghost** [comment]
Но устройство не появилось в devices - playground

**Comment by ghost** [comment]
Рандомные действия привели к появлению всех устройств, спасибо)
