### ISSUE TITLE
документация

### ISSUE THREAD

**Issue by edgiru** [devicehive/esp8266-firmware#9]
Пытаюсь разобраться эксперементальными способами. 
Без документации на русском языке крайне сложно понять что и как. Подскажите планируется ли вообще перевод, если да то примерно когда? Ну или хотя бы статью не большую что и как сделать. К примеру Dashboard весь вечер промучился искал информацию что и как где написать, не на русском не на англиском информации нет совсем. по ссылке https://github.com/devicehive/devicehive-freeboard-datasource посмотрел 2 картинки первая то понятно но вторая не описана что там за код вписали в Gauge.

**Comment by Nikolay-Kha** [comment]
Перевода именно документации на русский не будет. Будет еще одна статья о использование прошивки на русском.
Касаемо Dashboard, это на самом деле есть не что иное как Freeboard - https://github.com/Freeboard/freeboard
причем репозитории который вы указали - всего лишь коннектор сервера к данному проекту. Сразу подключенный к самому Фрибоарду коннектор в этом репозитории - https://github.com/devicehive/freeboard
Freeboard это стороний проект, имеющий собственную документаци, мы лишь написали коннектор для нашего сервера.

**Comment by edgiru** [comment]
Ох как жаль. Придется изучать и переводить словарем. (( последний вопрос именно про Ваш коннектор к freeboard.

![image](https://cloud.githubusercontent.com/assets/4624056/11033542/0adb63c6-86f5-11e5-994a-f88681e31dc2.png)
При выборе плагина DeviceHive в datasources в поле "Device IDS" я так понял забивать Device ID моего модуля? А в Notification names что писать (я забиваю произвольное имя)? во все остальные поля данные сами автоматом проставляются такие как  key и APIurl. Но на главной странице freeboard "последнее обновление" пишется never, так и должно быть? 
![3333](https://cloud.githubusercontent.com/assets/4624056/11033568/43c2e9e8-86f5-11e5-8214-ea67cdd81b86.JPG)

Извини уж что я с этими вопросами к Вам, не знаю у кого спросить. А про документацию к freeboard спасибо буду изучать из источника оригинала.

**Comment by Nikolay-Kha** [comment]
Проект коннектора для фрибоарда делался не для esp8266. Текущая реализация коннектора позволяет отображать только нотификации из сервера DH. Поэтому отображение данных от esp8266 в текущей реализации затруденено. Из интересного сейчас, можно например отображать данные с ADC на графиках. Нужно запустить измерение ADC с каким-то интервалом времени на чипе, послав комманду откуда-то извне(из той же админки например). Затем фриборд увидев наличие нотификаций сможет что-то отрисовать. В частости 'last update' должен будет начать обновляться. В notification names ничего писать не надо. Далее, нужно создать какой нибудь контрол ("add pane"), в нём создать виджет (кнопка плюсик там есть), выбрать тип, затем внутри value написать на js код который будет превращать нотификаций в числа для отсчетов. Входной объект datasource. Результатом должно быть что-то численное.
![image](https://cloud.githubusercontent.com/assets/8740775/11034538/52acfce8-86fd-11e5-9c00-1610cb9a85f3.png)
вот пример настройки гауджа - 
![image](https://cloud.githubusercontent.com/assets/8740775/11034557/7f6cc128-86fd-11e5-9e1f-84adda66dee2.png)
код - datasources["demo"]["parameters"]["0"] - это пример для визуализации данных с adc esp8266 при условии что весь боард назван "demo"
во время набора кода, если нотификации были (тогда и "last updated" будет обновлен) фрибоард сам будет подсказывать код.

**Comment by edgiru** [comment]
Спасибо огромное Николай!
